
function DummyEntryDataOs(){
  
  const tableDataListsBasicInfo = [
    { 'thead': '姓(漢字)', 'tdata': '応募' },
    { 'thead': '名(漢字)', 'tdata': '花子' },
    { 'thead': 'セイ(カナ)', 'tdata': 'オウボ' },
    { 'thead': 'メイ(カナ)', 'tdata': 'ハナコ' },
    { 'thead': '性別','tdata': '女性' },  
    { 'thead': '生年月日', 'tdata': '2000年01月01日' },
    { 'thead': '住所(郵便番号)', 'tdata': '103-0013' },
    { 'thead': '住所(都道府県)','tdata': '東京都' },
    { 'thead': '住所(市区町村)','tdata': '中央区日本橋人形町' },
    { 'thead': '住所(町域・番地)','tdata': '3-3-13' },
    { 'thead': '住所(建物等)', 'tdata': '人形町フォレストビル2F' },
    { 'thead': '最寄り駅①(沿線)', 'tdata': '東京メトロ日比谷線' },
    { 'thead': '最寄り駅①(駅名)', 'tdata': '人形町駅' },
    { 'thead': '最寄り駅からの交通手段①', 'tdata': '徒歩' },
    { 'thead': '最寄り駅からの所要時間①', 'tdata': '5分' },
    { 'thead': '最寄り駅②(沿線)', 'tdata': '東京メトロ半蔵門線' },
    { 'thead': '最寄り駅②(駅名)', 'tdata': '水天宮前駅' },
    { 'thead': '電話番号(携帯)', 'tdata': '090-3333-3333' },
    { 'thead': '電話番号(その他連絡先)', 'tdata': '03-3333-3333' },
    { 'thead': 'メールアドレス1', 'tdata': 'oubo@ilovex.co.jp' },
    { 'thead': 'メールアドレス2', 'tdata': 'dammy-test-fake@docomo.co.jp' },
    { 'thead': 'メールアドレス1種別', 'tdata': 'PC' },
    { 'thead': 'メールアドレス2種別', 'tdata': '携帯' },
    { 'thead': '在留カード情報', 'tdata': '在留資格区分' },
  ];

  const tableDataListsOS2 = [
    { 'thead': '希望の雇用形態', 'tdata': '直接雇用(正社員)' },
    { 'thead': '希望勤務時間', 'tdata': '長期(6ヵ月以上)' },
    { 'thead': 'NG職種', 'tdata': '早番・日勤・遅番・夜勤' },
    { 'thead': '希望条件','tdata': '' },
    { 'thead': '【希望職種】事務職','tdata': '一般事務 / 営業事務 / 貿易・国際事務 / 特許事務英文事務 / 通訳・翻訳 / 金融事務（銀行・証券）金融事務（生保・損保）経理事務・財経・会計 / 総務・人事広報・宣伝 / 秘書 / 受付 / データ入力 / 企画・マーケティング事務的軽作業（封入など）/ 労務（保険手続き・給与計算） / 旅行事務 / 医療事務 / 学校事務' },
    { 'thead': '【希望職種】事務職','tdata': 'テレマーケティング（アウト） / テレマーケティング（イン） / テレマーケティング（SV） / テレマーケティング（保険） / テレマーケティング（証券） / カスタマーサポート（受電1次・受電2次） / カスタマーサポート（メール対応） / ヘルプデスク' },
    { 'thead': '【希望職種】事務職','tdata': '販売（アパレル・コスメ） / 携帯販売（docomo） / 携帯販売（au） / 携帯販売（softbonk） / 携帯販売（その他キャリア） / 販売（家電・PCなど） / 販売（食品） / 接客（ショールーム・カウンター） / フード・飲食（接客） / 営業（企画営業） / 営業（ルート営業） / 製造・物流作業 / 軽作業 / CADオペレーター / CAD設計 / システムエンジニア / プログラマー / 実務応用操作/取得・評価 / キッティング / Webデザイナー / Webディレクター / Web制作・編集 / 編集・制作・校正 / DTPオペレーター / その他' },
    { 'thead': '就業開始可能日', 'tdata': '2023年04月01日' },
    { 'thead': '希望勤務可能日', 'tdata': '月・火・水・木・金・土' },
    { 'thead': '希望勤務日数','tdata': '週5日' },
    { 'thead': '希望勤務形態', 'tdata': 'フルタイム(時間固定・平日)' },
    { 'thead': '希望勤務時間', 'tdata': '' },
    { 'thead': '残業可否','tdata': '場合により可(26時まで可能)' },
    { 'thead': '夜勤可否','tdata': '場合により可(26時まで可能)' },
    { 'thead': '希望条件','tdata': '時給：' },
    { 'thead': null,'tdata': '月給：' },
    { 'thead': null,'tdata': '勤務地：' },
  ];

  const tableDataListsOS3 = [
    { 'thead': '【スキルチェック】Word', 'tdata': null },
    { 'thead': '文字入力', 'tdata': '実務応用操作/取得' },
    { 'thead': '文章作成','tdata': '実務応用操作/取得' },
    { 'thead': '編集・作表', 'tdata': '実務応用操作/取得' },
    { 'thead': '書式設定の応用','tdata': '実務応用操作/取得' },
    { 'thead': '図・表挿入','tdata': '実務応用操作/取得' },
    { 'thead': '図形（オートシェイプ）','tdata': '実務応用操作/取得' },
    { 'thead': '差込印刷', 'tdata': '実務応用操作/取得' },
    { 'thead': 'マクロの作成', 'tdata': '実務応用操作/取得' },
    { 'thead': '【スキルチェック】Excel','tdata': null },
    { 'thead': 'データ入力', 'tdata': '実務応用操作/取得' },
    { 'thead': '表作成', 'tdata': '実務応用操作/取得' },
    { 'thead': '表計算・四則演算','tdata': '実務応用操作/取得' },
    { 'thead': 'グラフ作成','tdata': '実務応用操作/取得' },
    { 'thead': 'セルの書式設定','tdata': '実務応用操作/取得' },
    { 'thead': 'セルの書式設定・表示形式','tdata': '実務応用操作/取得' },
    { 'thead': 'セルの書式設定・列幅・行高変更','tdata': '実務応用操作/取得' },
    { 'thead': 'セルの書式設定・網掛け','tdata': '実務応用操作/取得' },
    { 'thead': 'セルの書式設定・フォントスタイル変更','tdata': '実務応用操作/取得' },
    { 'thead': 'セルの書式設定・配置設定','tdata': '実務応用操作/取得' },
    { 'thead': 'セルの書式設定・小数点表示','tdata': '実務応用操作/取得' },
    { 'thead': 'セルの書式設定・セル結合','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・SUM','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・AVERAGE','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・ROUND','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・COUNTIF','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・SUMIF','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・IF','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・VLOOKUP','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・ピポットテーブル','tdata': '実務応用操作/取得' },
    { 'thead': '関数/数式・複数条件関数（OR,AND）','tdata': '実務応用操作/取得' },
    { 'thead': 'マクロ作成','tdata': '実務応用操作/取得' },
    { 'thead': 'VBAオブジェクト','tdata': '実務応用操作/取得' },
    { 'thead': '【スキルチェック】PowerPoint','tdata': null },
    { 'thead': 'オブジェクト作成・編集','tdata': '実務応用操作/取得' },
    { 'thead': '新規スライド作成','tdata': '実務応用操作/取得' },
    { 'thead': 'スライドショー作成','tdata': '実務応用操作/取得' },
    { 'thead': 'マスタアニメーション作成','tdata': '実務応用操作/取得' },
    { 'thead': 'プレゼンテーション作成','tdata': '実務応用操作/取得' },
    { 'thead': '【スキルチェック】Access','tdata': null },
    { 'thead': 'テーブル・データ入力', 'tdata': '実務応用操作/取得' },
    { 'thead': 'テーブル・インポート・エクスポート', 'tdata': '実務応用操作/取得' },
    { 'thead': 'テーブル・データ型　設定', 'tdata': '実務応用操作/取得' },
    { 'thead': 'テーブル・リレーションシップ設定', 'tdata': '実務応用操作/取得' },
    { 'thead': 'フォームウィザード', 'tdata': '実務応用操作/取得' },
    { 'thead': 'サブフォームの作成', 'tdata': '実務応用操作/取得' },
    { 'thead': 'クエリ・並べ替えの設定', 'tdata': '実務応用操作/取得' },
    { 'thead': 'クエリ・パラメータクエリ作成', 'tdata': '実務応用操作/取得' },
    { 'thead': 'クエリ・テーブル結合・データ抽出', 'tdata': '実務応用操作/取得' },
    { 'thead': 'クエリ・更新・削除・追加', 'tdata': '実務応用操作/取得' },
    { 'thead': 'レポート・ラベル用レポート作成', 'tdata': '実務応用操作/取得' },
    { 'thead': 'レポート・改ページ設定', 'tdata': '実務応用操作/取得' },
    { 'thead': 'レポート・印刷領域設定', 'tdata': '実務応用操作/取得' },
    { 'thead': 'レポート・マクロ設定', 'tdata': '実務応用操作/取得' },
    { 'thead': '【スキルチェック】OS環境','tdata': null },
    { 'thead': 'Windows　XP', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Windows　7', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Windows　8', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Mac', 'tdata': '実務応用操作/取得' },
    { 'thead': 'その他', 'tdata': '実務応用操作/取得' },
    { 'thead': 'その他の内容', 'tdata': '実務応用操作/取得' },
    { 'thead': '【スキルチェック】ソフトウェアツール','tdata': null },
    { 'thead': 'メーラー・Microsoft Outlook', 'tdata': '実務応用操作/取得' },
    { 'thead': 'メーラー・Windows Live Mail', 'tdata': '実務応用操作/取得' },
    { 'thead': 'メーラー・その他', 'tdata': '実務応用操作/取得' },
    { 'thead': 'メーラー・その他・ソフト名', 'tdata': '実務応用操作/取得' },
    { 'thead': 'ASP・SAP', 'tdata': '実務応用操作/取得' },
    { 'thead': 'ASP・ファイルメーカー', 'tdata': '実務応用操作/取得' },
    { 'thead': 'ASP・Lotus Notes', 'tdata': '実務応用操作/取得' },
    { 'thead': '【スキルチェック】プログラミング言語','tdata': null },
    { 'thead': 'HTML', 'tdata': '実務応用操作/取得' },
    { 'thead': 'CSS', 'tdata': '実務応用操作/取得' },
    { 'thead': 'javascript（Jquery）', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Anguler', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Ajax', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Java', 'tdata': '実務応用操作/取得' },
    { 'thead': 'php', 'tdata': '実務応用操作/取得' },
    { 'thead': 'ruby（on rails)', 'tdata': '実務応用操作/取得' },
    { 'thead': 'C、C#、C++', 'tdata': '実務応用操作/取得' },
    { 'thead': 'shell', 'tdata': '実務応用操作/取得' },
    { 'thead': 'SQLServer', 'tdata': '実務応用操作/取得' },
    { 'thead': 'MySQL', 'tdata': '実務応用操作/取得' },
    { 'thead': 'PostgreSQL', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Oracle', 'tdata': '実務応用操作/取得' },
    { 'thead': 'VB.net', 'tdata': '実務応用操作/取得' },
    { 'thead': 'C#.net', 'tdata': '実務応用操作/取得' },
    { 'thead': 'ObjectiveC', 'tdata': '実務応用操作/取得' },
    { 'thead': 'SWIFT', 'tdata': '実務応用操作/取得' },
    { 'thead': 'SQLite', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Apache、tomcat', 'tdata': '実務応用操作/取得' },
    { 'thead': 'nginx', 'tdata': '実務応用操作/取得' },
    { 'thead': 'WebLogic', 'tdata': '実務応用操作/取得' },
    { 'thead': 'OracleServer', 'tdata': '実務応用操作/取得' },
    { 'thead': 'その他', 'tdata': '実務応用操作/取得' },
    { 'thead': 'その他・言語名', 'tdata': '実務応用操作/取得' },
    { 'thead': '【スキルチェック】制作ソフト','tdata': null },
    { 'thead': 'Illustrator', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Illustrator・Ver', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Photoshop', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Photoshop・Ver', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Dreamweaver', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Fireworks', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Adobe Flash', 'tdata': '実務応用操作/取得' },
    { 'thead': 'InDesign', 'tdata': '実務応用操作/取得' },
    { 'thead': 'SAI', 'tdata': '実務応用操作/取得' },
    { 'thead': 'WordPress', 'tdata': '実務応用操作/取得' },
    { 'thead': 'Maya', 'tdata': '実務応用操作/取得' },
    { 'thead': '3DS MAX', 'tdata': '実務応用操作/取得' },
    { 'thead': 'After Effects', 'tdata': '実務応用操作/取得' },
    { 'thead': 'その他/CMSソフト名', 'tdata': '実務応用操作/取得' },
    { 'thead': 'その他/CMSソフト名・ソフト名', 'tdata': '実務応用操作/取得' },
    { 'thead': '【スキルチェック】CAD','tdata': null },
    { 'thead': 'CADソフト', 'tdata': '実務応用操作/取得' },
    { 'thead': 'CADソフト・ソフト名', 'tdata': '実務応用操作/取得' },
    { 'thead': '内容', 'tdata': '実務応用操作/取得' },
    { 'thead': '内容・内容', 'tdata': '実務応用操作/取得' },
  ];

  const tableDataListsOS4 = [
    { 'thead': 'OS用保有資格1', 'tdata': '普通自動車免許 (2018年3月取得)' },
    { 'thead': 'OS用保有資格2', 'tdata': '簿記 (2018年3月取得)' },
    { 'thead': 'OS用保有資格3', 'tdata': '実用英語技能検定 (2018年3月取得)' },
    { 'thead': 'OS用保有資格4', 'tdata': '宅地建物取引士 (2018年3月取得)' },
    { 'thead': 'PC入力スキル', 'tdata': 'ブラインドタッチ入力' },
    { 'thead': '英語スキル', 'tdata': 'ビジネス上での英語の読み書き・会話が可能' },
  ];
  
  const tableDataListsOS5 = [
    { 'thead': '【スキルチェック】一般事務', 'tdata': 'データ入力 / 資料作成 / 議事録作成 / 部内アシスタント' },
    { 'thead': '【スキルチェック】営業事務', 'tdata': '受注発注業務 / 海外受発注 / 見積作成 / 契約書作成 / 請求書作成 / 納期管理 / 営業アシスタント / クレーム対応' },
    { 'thead': '【スキルチェック】経理事務', 'tdata': '伝票起票 / 伝票仕訳 / 売掛金管理 / 買掛金管理 / 会計ソフト入力 / 会計ソフト入力・ソフト名 / 月次決算(補助含む) / 年次決算(補助含む) / 英文経理' },
    { 'thead': '【スキルチェック】総務事務', 'tdata': '経費精算 / 旅費計算 / 小口現金管理 / 備品管理・発注 / 郵便物仕分' },
    { 'thead': '【スキルチェック】人事事務', 'tdata': '給与計算 / 給与計算・名分 / 社会保険事務 / 年末調整 / 採用 / 説明会対応 / 面接 / 合否連絡 / 教育・研修 / 社宅管理' },
    { 'thead': '【スキルチェック】秘書', 'tdata': '役員付秘書(日本人) / 役員付秘書(外国人) / グループ付秘書 / スケジュール管理 / 慶弔対応 / 出張手配' },
    { 'thead': '【スキルチェック】受付', 'tdata': '総合受付 / ショールーム受付 / その他受付 / その他受付・内容' },
    { 'thead': '【スキルチェック】貿易事務', 'tdata': '輸出業務 / 輸入業務 / 三国間貿易 / 通関業務（乙仲）インボイス作成 / パッキングリスト / B/L作成 / AWB作成 / A/N作成 / S/I作成 / L/C関係 / 英語（メール・電話）' },
    { 'thead': '【スキルチェック】英文事務', 'tdata': '英文資料作成 / 翻訳 / 同時翻訳 / 語学レベル	TOEIC（900）点 / 英検（1）級' },
    { 'thead': '【スキルチェック】電話業務', 'tdata': 'テレマーケティング / テレフォンオペレーター / テレフォンアポインター / カスタマーサポート' },
    { 'thead': '【スキルチェック】コールセンター', 'tdata': 'ユーザーサポート / 債権回収 / クレーム対応' },
  ];

  const tableDataListsOS6 = [
    { 'thead': '職務経歴①', 'tdata': '' },
    { 'thead': '企業名', 'tdata': '' },
    { 'thead': '所属部署名', 'tdata': '' },
    { 'thead': '入社日', 'tdata': '' },
    { 'thead': '退職日', 'tdata': '' },
    { 'thead': '雇用形態', 'tdata': '' },
    { 'thead': '職務内容', 'tdata': '' },
    { 'thead': '職種カテゴリー', 'tdata': '' },
    { 'thead': '職種', 'tdata': '' },
    { 'thead': '使用したOAソフト', 'tdata': '' },
    { 'thead': 'スキル（IT系）', 'tdata': '' },
    { 'thead': '役割', 'tdata': '' },
    { 'thead': '月給', 'tdata': '' },
    { 'thead': '時給/月給ー金額', 'tdata': '' },
    { 'thead': '退職理由', 'tdata': '' },
    { 'thead': '職務経歴②', 'tdata': '' },
    { 'thead': '企業名', 'tdata': '' },
    { 'thead': '所属部署名', 'tdata': '' },
    { 'thead': '入社日', 'tdata': '' },
    { 'thead': '退職日', 'tdata': '' },
    { 'thead': '雇用形態', 'tdata': '' },
    { 'thead': '職務内容', 'tdata': '' },
    { 'thead': '職種カテゴリー', 'tdata': '' },
    { 'thead': '職種', 'tdata': '' },
    { 'thead': '使用したOAソフト', 'tdata': '' },
    { 'thead': 'スキル（IT系）', 'tdata': '' },
    { 'thead': '役割', 'tdata': '' },
    { 'thead': '月給', 'tdata': '' },
    { 'thead': '時給/月給ー金額', 'tdata': '' },
    { 'thead': '退職理由', 'tdata': '' },
    { 'thead': '最終学歴', 'tdata': '' },
    { 'thead': '学校名', 'tdata': '' },
    { 'thead': '最終学歴区分', 'tdata': '' },
    { 'thead': '専攻学部/学科', 'tdata': '' },
    { 'thead': '卒業年月', 'tdata': '' },
    { 'thead': '卒業区分', 'tdata': '' },
  
  ];

  const tableDataListsOS7 = [
    { 'thead': '転職状況（OS）', 'tdata': '有' },
    { 'thead': null, 'tdata': '応募中（　）社' },
    { 'thead': null, 'tdata': '面談待ち（　）社' },
    { 'thead': null, 'tdata': '面談済（　）社' },
    { 'thead': '持病の有無や服薬はしているか？', 'tdata': '持病	詳細' },
    { 'thead': null, 'tdata': '服薬	詳細' },
    { 'thead': '通院有無や入院歴', 'tdata': '通院	詳細' },
    { 'thead': null, 'tdata': '入院	詳細' },
    { 'thead': 'メンタルクリニック', 'tdata': '詳細' },
    { 'thead': '刺青の有無', 'tdata': '詳細（どこにどれくらいの大きさ）' },
    { 'thead': '現在の髪色', 'tdata': '' },
    { 'thead': 'ネイルの状態', 'tdata': '' },
    { 'thead': '喫煙有無', 'tdata': '' },
    { 'thead': 'コロナワクチンの接種有無', 'tdata': '' },
    { 'thead': '希望条件の優先順位（1位）', 'tdata': '' },
    { 'thead': null, 'tdata': 'その他テキスト：' },
    { 'thead': '希望条件の優先順位（2位）', 'tdata': '' },
    { 'thead': null, 'tdata': 'その他テキスト：' },
    { 'thead': '希望条件の優先順位（3位）', 'tdata': '' },
    { 'thead': null, 'tdata': 'その他テキスト：' },
    { 'thead': '仕事探しをしている理由', 'tdata': '' },
    { 'thead': '希望交通手段', 'tdata': '公共交通機関 / 車 / 自転車 / 徒歩' },
    { 'thead': '業務確定日の可能日程', 'tdata': '' },
    { 'thead': '自己PR/特記事項', 'tdata': '' },
    { 'thead': '特記事項（任意）', 'tdata': '' },
    { 'thead': '当社記入欄', 'tdata': '' },
    { 'thead': '在留カード情報', 'tdata': '在留資格確認済み' },
    { 'thead': '見込みランク', 'tdata': '' },
    { 'thead': '    ', 'tdata': '' },
  ];

  
  const tabPanelListsOs = [
    tableDataListsBasicInfo,
    tableDataListsOS2,
    tableDataListsOS3,
    tableDataListsOS4,
    tableDataListsOS5,
    tableDataListsOS6,
    tableDataListsOS7,
    // tableDataListsOS8,
    // tableDataListsOS9,
    // tableDataListsOS10,
    // tableDataListsOS11,

  ];
  return tabPanelListsOs;
}

export default DummyEntryDataOs;